// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6VwPJp20Ojj56xmYuCPulACjm_Ym_6lw',
    appId: '1:19297507129:android:8ac34234183ef0fdbd7ae8',
    messagingSenderId: '19297507129',
    projectId: 'mari-62976',
    storageBucket: 'mari-62976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwPbVkUpac3uKAjsG4z6OEu1nkCudz-ZU',
    appId: '1:19297507129:ios:183905684dac0ba7bd7ae8',
    messagingSenderId: '19297507129',
    projectId: 'mari-62976',
    storageBucket: 'mari-62976.firebasestorage.app',
    iosBundleId: 'com.example.helloApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYchZehRrWOgUUEjhGhxhqv3b-raMM-1k',
    appId: '1:19297507129:web:39b776161bbb48f9bd7ae8',
    messagingSenderId: '19297507129',
    projectId: 'mari-62976',
    authDomain: 'mari-62976.firebaseapp.com',
    storageBucket: 'mari-62976.firebasestorage.app',
    measurementId: 'G-84DHPTDRP5',
  );
}
